# -*- coding: utf-8 -*-
"""LVADSUSR77_Bertina_lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NCJYQsvw9VmL2VcquK9sH4QQCYoMHVUF
"""

#importing modules
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

#to supress warnings
import warnings as wr
wr.filterwarnings("ignore")

#Reading the Data
file_path = "/content/auto-mpg.csv"
data = pd.read_csv(file_path)
data.head()

data.columns

print("Missing values before using ffill: ")
missing_values = data.isnull().sum()
missing_values

data.fillna(method='ffill', inplace=True)

print("Missing values after using ffill: ")
missing_values = data.isnull().sum()
missing_values

data.shape

Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1

outliers = ((data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))).any(axis=1)
print(outliers)

data = data[~outliers]

data.shape

#Exploratory Data Analysis
print("Shape of the data:", data.shape)
print("Descriptive statistics:\n", data.describe())

data.drop(columns=['car name'], inplace=True)

sns.histplot(data['mpg'], kde=True)
plt.title('Fuel Efficiency (mpg)')
plt.xlabel('mpg')
plt.ylabel('Frequency')
plt.show()

X = data.drop('mpg', axis=1)
y = data['mpg']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = LinearRegression()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))